# Generated by Django 5.1.4 on 2024-12-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='not specified', max_length=50)),
                ('length', models.FloatField(default='not specified', max_length=20)),
                ('weight', models.IntegerField(default='not specified')),
                ('condition', models.CharField(default='not specified', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default='not specified', max_digits=10)),
                ('image_urls', models.TextField(blank=True, default='', max_length=500)),
                ('owner', models.CharField(default='admin', max_length=50)),
            ],
        ),
    ]
