# Generated by Django 5.1.4 on 2024-12-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_object_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='image_urls',
            field=models.JSONField(default=list),
        ),
    ]
