# Generated by Django 5.1.4 on 2024-12-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_object_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='description',
            field=models.CharField(default='not specified', max_length=500),
        ),
    ]
