# Generated by Django 5.1.4 on 2024-12-27 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_object_date_time_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='date_time_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='object',
            name='price',
            field=models.DecimalField(decimal_places=2, default='not specified', max_digits=9),
        ),
    ]
