# Generated by Django 5.1.4 on 2024-12-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_object_date_time_posted_alter_object_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='saved',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
