# Generated by Django 5.1.4 on 2024-12-27 16:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_object_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='flex',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=2),
        ),
        migrations.AlterField(
            model_name='object',
            name='length',
            field=models.FloatField(default='0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='object',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='object',
            name='weight',
            field=models.IntegerField(default='-1'),
        ),
    ]
