# Generated by Django 5.1.4 on 2024-12-27 16:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_object_flex_alter_object_length_alter_object_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='flex',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
    ]
