# Generated by Django 5.1.4 on 2025-01-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_object_flex'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='city',
            field=models.CharField(default='not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='object',
            name='state',
            field=models.CharField(default='not specified', max_length=50),
        ),
    ]
