# Generated by Django 5.1.4 on 2025-02-05 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_object_city_object_state'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='object',
            table='Listings',
        ),
    ]
