# Generated by Django 5.1.4 on 2025-03-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_object_itemcategory_object_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='size',
            field=models.CharField(default='n/a', max_length=30),
        ),
    ]
